
server:
  port: 9090
  shutdown: graceful
  
jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHa

# logging:
#   config: classpath:logback-api.xml

mybatis:
  type-aliases-package: com.cyh.base.dto
  # type-aliases-package: com.cyh.base.**.dto
  mapper-locations: classpath:/mapper/**/*.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

spring :
  application:
    name: base

  profiles:
    active:
      - local
    # group:
    #   "local": "local"
      # "dev": "dev"
      # "stg": "stg"
      # "prd": "prd"
#   mvc:
#     view:
# #      prefix: /WEB-INF/view/
#       suffix: .html
---

# 로컬세팅
spring :
  config:
    activate:
      on-profile:
        - local

  devtools:
    livereload:
      enabled: true
    restart:
      enabled: true

  # datasource :
  #     driver-class-name : org.postgresql.Driver
  #     url : jdbc:postgresql://34.41.156.106:5432/postgres
  #     username : "postgres"
  #     password : "rhdiddl03"

  # datasource :      
  #       driver-class-name : net.sf.log4jdbc.sql.jdbcapi.DriverSpy
  #       url : jdbc:log4jdbc:postgresql://34.41.156.106:5432/postgres
  #       username : "postgres"
  #       password : "rhdiddl03"


  datasource :      
        driver-class-name : net.sf.log4jdbc.sql.jdbcapi.DriverSpy
        url : jdbc:log4jdbc:postgresql://aws-0-ap-northeast-2.pooler.supabase.com:5432/postgres
        username : "postgres.mngfzhpcgrcbciwhfdfr"
        password : "##Rhdiddl03"
        hikari:
          minimum-idle: 5        # 최소 유지할 커넥션 개수
          maximum-pool-size: 10  # 최대 커넥션 개수
          idle-timeout: 30000    # 커넥션이 유휴 상태일 때 제거되기까지의 시간 (30초)
          max-lifetime: 1800000  # 커넥션 최대 수명 (30분)
          connection-timeout: 30000 # 커넥션을 얻을 때까지 기다리는 최대 시간 (30초)
          auto-commit: true      # 자동 커밋 여부
---







